### ISSUE TITLE
Calling async-all with null

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/async-all#1]
I'm not sure how you want this handled, but it's not caught because `typeof null === object`.

``` js
> var all = require('async-all')
undefined
> all(null, console.log)
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at all (C:\Users\Michael\Github\JS_Source\node_modules\async-all\index.js:37:9)
    at repl:1:18
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
>
```

**Comment by TehShrike** [comment]
Yeah, there should be a check for that.
